[project]
name = "afac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "openai>=1.86.0",
    "pandas>=2.3.0",
    "pip>=25.1.1",
    "tqdm>=4.67.1",
]
